name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Build Package
        id: npm-package
        run: npm run package

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    # Only run action tests on pull requests to avoid unnecessary runs
    if: github.event_name == 'pull_request'
    needs: test-typescript

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          milliseconds: '2000'
          example-input: 'test-value'

      - name: Print Outputs
        id: output
        run: |
          Write-Output "Time: ${{ steps.test-action.outputs.time }}"
          Write-Output "Result: ${{ steps.test-action.outputs.result }}"
          Write-Output "Processed: ${{ steps.test-action.outputs.processed }}"

      - name: Verify Outputs
        id: verify
        run: |
          $time = '${{ steps.test-action.outputs.time }}'
          $result = '${{ steps.test-action.outputs.result }}'
          $processed = '${{ steps.test-action.outputs.processed }}'

          if ([string]::IsNullOrEmpty($time)) {
            Write-Error "Time output is empty"
            exit 1
          }

          if ([string]::IsNullOrEmpty($result)) {
            Write-Error "Result output is empty"
            exit 1
          }

          if ($processed -ne 'true') {
            Write-Error "Processed output should be 'true', got: $processed"
            exit 1
          }

          Write-Output "All outputs verified successfully!"

  test-cross-platform:
    name: Cross-Platform Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Tests
        id: npm-test
        run: npm run test
